<a href="https://colab.research.google.com/github/njokinjuguna/Machine-learning-Models/blob/main/K_fold_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [90]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()


In [91]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(digits.data,digits.target,test_size=0.3)

In [92]:
lr=LogisticRegression()
lr.fit(X_train,y_train)
lr.score(X_test,y_test)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9611111111111111

In [93]:
svm=SVC()
svm.fit(X_train,y_train)
svm.score(X_test,y_test)

0.9833333333333333

In [94]:
rf=RandomForestClassifier()
rf.fit(X_train,y_train)
rf.score(X_test,y_test)

0.9722222222222222

##**the K-Fold api**

In [95]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [96]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


from sklearn.model_selection import KFold
kf=KFold(n_splits=5)
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
  print(train_index,test_index)

[2 3 4 5 6 7 8] [0 1]

[0 1 4 5 6 7 8] [2 3]

[0 1 2 3 6 7 8] [4 5]

[0 1 2 3 4 5 8] [6 7]

[0 1 2 3 4 5 6 7] [8]


how is it able to get for example [2,3,4,5,6,7,8] as the training and [0,1] as the test
................................................................................................................................................................

In the example, you're using KFold from sklearn.model_selection, which is a cross-validation technique that splits data into a set number of n_splits (in this case, 5). Let's break down how it works step by step:

Explanation of KFold:
KFold Cross-Validation: This method splits the data into
𝑛
n equal-sized parts (folds). In each iteration, one fold is used as the test set, while the remaining
𝑛
−
1

n−1 folds are used as the training set. This process is repeated
𝑛
n times, ensuring that each fold is used exactly once as the test set.

n_splits=5: This means the data will be divided into 5 folds, where each iteration will select one fold for testing and the remaining 4 folds for training.

Data: You are passing the list [1, 2, 3, 4, 5, 6, 7, 8, 9] as the data. It has 9 elements, and you want 5 splits (folds). Each fold will contain approximately
9
5
=
1.8
5
9
​
 =1.8 items. Since it's impossible to perfectly split 9 items into 5 parts, some folds will contain 2 items, and others will contain 1 item.

Step-by-Step Breakdown:
1st Iteration:

Training indices: [2, 3, 4, 5, 6, 7, 8]
Test indices: [0, 1]
Here, the test set contains the first two indices [0, 1], corresponding to the first two elements of the data [1, 2]. The remaining data [3, 4, 5, 6, 7, 8, 9] is used for training.

2nd Iteration:

Training indices: [0, 1, 4, 5, 6, 7, 8]
Test indices: [2, 3]
Now, the test set contains indices [2, 3], corresponding to elements [3, 4]. The rest of the data [1, 2, 5, 6, 7, 8, 9] is used for training.

3rd Iteration:

Training indices: [0, 1, 2, 3, 6, 7, 8]

Test indices: [4, 5]

Test set contains indices [4, 5], corresponding to elements [5, 6]. The rest of the data [1, 2, 3, 4, 7, 8, 9] is used for training.

4th Iteration:

Training indices: [0, 1, 2, 3, 4, 5, 8]

Test indices: [6, 7]

Test set contains indices [6, 7], corresponding to elements [7, 8]. The rest of the data [1, 2, 3, 4, 5, 6, 9] is used for training.

5th Iteration:

Training indices: [0, 1, 2, 3, 4, 5, 6, 7]
Test indices: [8]
Test set contains index [8], corresponding to the element [9]. The remaining data [1, 2, 3, 4, 5, 6, 7, 8] is used for training.

.........................more explanation......................................

How does it get [2, 3, 4, 5, 6, 7, 8] as training and [0, 1] as test?
The KFold function splits the data into approximately equal parts. In the first split, it uses the first two elements as the test set [0, 1] (which corresponds to the first two numbers [1, 2] in the original data). The remaining elements form the training set [2, 3, 4, 5, 6, 7, 8] (which corresponds to numbers [3, 4, 5, 6, 7, 8, 9]).

In each subsequent iteration, KFold shifts the test set by using different indices, ensuring that each data point is used exactly once for testing.

This is how KFold ensures that every data point gets a chance to be in the test set while using the rest for training in each fold.

### **Generic function that can use to iterate through our 3 classfiers**

In [97]:
def get_score(model,X_train,X_test,y_train,y_test):
  model.fit(X_train,y_train)
  return model.score(X_test,y_test)

In [98]:
get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test)

0.9777777777777777

### **now lets simplify all this by using StratifiedKFold**
the StratifiedKFold is similar to KFold however its able to separate the folds its able to divide each of the classifications categories in a uniform way

In [99]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)


In [100]:
scores_lg=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in folds.split(digits.data,digits.target):
  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]

  scores_lg.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))
  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

In [101]:
scores_lg

[0.9215358931552587, 0.9415692821368948, 0.9165275459098498]

In [102]:
scores_rf

[0.9398998330550918, 0.9565943238731218, 0.9282136894824707]

In [103]:
scores_svm

[0.9649415692821369, 0.9799666110183639, 0.9649415692821369]

### notice the difference between kf and StratifiedKFold

.........................................


StratifiedKFold is particularly useful when you have imbalanced classes. It ensures that each fold has a representative proportion of each class, which can lead to more reliable model evaluations, especially for classification problems.

KFold doesn't take the class labels into consideration when splitting, which can result in some folds being imbalanced (i.e., certain folds may have more examples of one class than others). This imbalance can distort the model's performance evaluation.


.........................................

KFold:
KFold only requires one parameter: the features (e.g., X).
KFold does not take class labels into account, so you only need to provide the feature set (e.g., digits.data), and it will randomly split the data into n_splits parts without considering the distribution of the target variable.

from sklearn.model_selection import KFold

kf = KFold(n_splits=3)

for train_index, test_index in kf.split(digits.data):


.........................................

StratifiedKFold:
StratifiedKFold requires two parameters: the features (e.g., X) and the target labels (e.g., y).
StratifiedKFold ensures that each fold has the same proportion of each class as the original dataset. To do this, it needs both the features (X) and the target labels (y).

from sklearn.model_selection import StratifiedKFold

skf = StratifiedKFold(n_splits=3)

for train_index, test_index in skf.split(digits.data, digits.target):

### cross_val_score

we can use the cross_val_score() method from sklearn to perform the same as what we did before,this:


scores_lg=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in folds.split(digits.data,digits.target):

  X_train,X_test,y_train,y_test=digits.data[train_index],digits.data[test_index],digits.target[train_index],digits.target[test_index]


  scores_lg.append(get_score(LogisticRegression(),X_train,X_test,y_train,y_test))

  scores_svm.append(get_score(SVC(),X_train,X_test,y_train,y_test))
  
  scores_rf.append(get_score(RandomForestClassifier(),X_train,X_test,y_train,y_test))

In [104]:
from sklearn.model_selection import cross_val_score

In [109]:
cross_val_score(SVC(),digits.data,digits.target)


array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [110]:
cross_val_score(RandomForestClassifier(),digits.data,digits.target)


array([0.91944444, 0.91388889, 0.95543175, 0.96100279, 0.93871866])

In [111]:
cross_val_score(LogisticRegression(),digits.data,digits.target)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _c

array([0.92222222, 0.86944444, 0.94150418, 0.93871866, 0.89693593])